# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12test_message.proto\x12\x0ctest_message\"\x15\n\x05testM\x12\x0c\n\x04word\x18\x01 \x01(\t2J\n\x13\x44\x61taTransferService\x12\x33\n\x07Message\x12\x13.test_message.testM\x1a\x13.test_message.testMB\x02H\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _globals['_TESTM']._serialized_start=36
  _globals['_TESTM']._serialized_end=57
  _globals['_DATATRANSFERSERVICE']._serialized_start=59
  _globals['_DATATRANSFERSERVICE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
